name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.12, 1.17]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build test binary
      run: go test -c

    # This package requires elevated privileges to do basically anything, and
    # since we share this CI workflow between Linux and macOS, just use sudo
    # since that's easier than setting a Linux capability.
    - name: Run tests
      run: sudo ./packet.test -test.race -test.v

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.17]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # Although this package doesn't support Windows, we want to verify that
    # everything builds properly.
    - name: Verify build for non-UNIX platforms
      run: go build
      env:
        GOOS: windows
